// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/publish-lifecycle-action": {
    params: {};
  };
  "/api/campaign-revert-preview": {
    params: {};
  };
  "/api/window-lifecycle-action": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/api/campaign-history": {
    params: {};
  };
  "/api/schedule-history": {
    params: {};
  };
  "/api/schedule-pricing": {
    params: {};
  };
  "/api/push-storefront": {
    params: {};
  };
  "/api/proxy/settings": {
    params: {};
  };
  "/auth/session-token": {
    params: {};
  };
  "/api/preview-price": {
    params: {};
  };
  "/api/staging-price": {
    params: {};
  };
  "/api/retry-failed": {
    params: {};
  };
  "/api/push-status": {
    params: {};
  };
  "/api/bulk-price": {
    params: {};
  };
  "/api/undo-price": {
    params: {};
  };
  "/api/products": {
    params: {};
  };
  "/api/billing": {
    params: {};
  };
  "/api/metrics": {
    params: {};
  };
  "/api/test-db": {
    params: {};
  };
  "/api/health": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/campaign-history": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/billing": {
    params: {};
  };
  "/app/rules": {
    params: {};
  };
  "/app/bulk": {
    params: {};
  };
  "/app/help": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/publish-lifecycle-action" | "/api/campaign-revert-preview" | "/api/window-lifecycle-action" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/api/campaign-history" | "/api/schedule-history" | "/api/schedule-pricing" | "/api/push-storefront" | "/api/proxy/settings" | "/auth/session-token" | "/api/preview-price" | "/api/staging-price" | "/api/retry-failed" | "/api/push-status" | "/api/bulk-price" | "/api/undo-price" | "/api/products" | "/api/billing" | "/api/metrics" | "/api/test-db" | "/api/health" | "/auth/login" | "/auth/*" | "/app" | "/app/campaign-history" | "/app/additional" | "/app/settings" | "/app/billing" | "/app/rules" | "/app/bulk" | "/app/help";
  };
  "routes/api.publish-lifecycle-action.ts": {
    id: "routes/api.publish-lifecycle-action";
    page: "/api/publish-lifecycle-action";
  };
  "routes/api.campaign-revert-preview.ts": {
    id: "routes/api.campaign-revert-preview";
    page: "/api/campaign-revert-preview";
  };
  "routes/api.window-lifecycle-action.ts": {
    id: "routes/api.window-lifecycle-action";
    page: "/api/window-lifecycle-action";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/api.campaign-history.ts": {
    id: "routes/api.campaign-history";
    page: "/api/campaign-history";
  };
  "routes/api.schedule-history.ts": {
    id: "routes/api.schedule-history";
    page: "/api/schedule-history";
  };
  "routes/api.schedule-pricing.ts": {
    id: "routes/api.schedule-pricing";
    page: "/api/schedule-pricing";
  };
  "routes/api.push-storefront.ts": {
    id: "routes/api.push-storefront";
    page: "/api/push-storefront";
  };
  "routes/api.proxy.settings.ts": {
    id: "routes/api.proxy.settings";
    page: "/api/proxy/settings";
  };
  "routes/auth.session-token.ts": {
    id: "routes/auth.session-token";
    page: "/auth/session-token";
  };
  "routes/api.preview-price.ts": {
    id: "routes/api.preview-price";
    page: "/api/preview-price";
  };
  "routes/api.staging-price.ts": {
    id: "routes/api.staging-price";
    page: "/api/staging-price";
  };
  "routes/api.retry-failed.ts": {
    id: "routes/api.retry-failed";
    page: "/api/retry-failed";
  };
  "routes/api.push-status.ts": {
    id: "routes/api.push-status";
    page: "/api/push-status";
  };
  "routes/api.bulk-price.ts": {
    id: "routes/api.bulk-price";
    page: "/api/bulk-price";
  };
  "routes/api.undo-price.ts": {
    id: "routes/api.undo-price";
    page: "/api/undo-price";
  };
  "routes/api.products.ts": {
    id: "routes/api.products";
    page: "/api/products";
  };
  "routes/api.billing.ts": {
    id: "routes/api.billing";
    page: "/api/billing";
  };
  "routes/api.metrics.ts": {
    id: "routes/api.metrics";
    page: "/api/metrics";
  };
  "routes/api.test-db.ts": {
    id: "routes/api.test-db";
    page: "/api/test-db";
  };
  "routes/api.health.ts": {
    id: "routes/api.health";
    page: "/api/health";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/campaign-history" | "/app/additional" | "/app/settings" | "/app/billing" | "/app/rules" | "/app/bulk" | "/app/help";
  };
  "routes/app.campaign-history.tsx": {
    id: "routes/app.campaign-history";
    page: "/app/campaign-history";
  };
  "routes/app.additional.tsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.settings.tsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app.billing.tsx": {
    id: "routes/app.billing";
    page: "/app/billing";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.rules.tsx": {
    id: "routes/app.rules";
    page: "/app/rules";
  };
  "routes/app.bulk.tsx": {
    id: "routes/app.bulk";
    page: "/app/bulk";
  };
  "routes/app.help.tsx": {
    id: "routes/app.help";
    page: "/app/help";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/api.publish-lifecycle-action": typeof import("./app/routes/api.publish-lifecycle-action.ts");
  "routes/api.campaign-revert-preview": typeof import("./app/routes/api.campaign-revert-preview.ts");
  "routes/api.window-lifecycle-action": typeof import("./app/routes/api.window-lifecycle-action.ts");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/api.campaign-history": typeof import("./app/routes/api.campaign-history.ts");
  "routes/api.schedule-history": typeof import("./app/routes/api.schedule-history.ts");
  "routes/api.schedule-pricing": typeof import("./app/routes/api.schedule-pricing.ts");
  "routes/api.push-storefront": typeof import("./app/routes/api.push-storefront.ts");
  "routes/api.proxy.settings": typeof import("./app/routes/api.proxy.settings.ts");
  "routes/auth.session-token": typeof import("./app/routes/auth.session-token.ts");
  "routes/api.preview-price": typeof import("./app/routes/api.preview-price.ts");
  "routes/api.staging-price": typeof import("./app/routes/api.staging-price.ts");
  "routes/api.retry-failed": typeof import("./app/routes/api.retry-failed.ts");
  "routes/api.push-status": typeof import("./app/routes/api.push-status.ts");
  "routes/api.bulk-price": typeof import("./app/routes/api.bulk-price.ts");
  "routes/api.undo-price": typeof import("./app/routes/api.undo-price.ts");
  "routes/api.products": typeof import("./app/routes/api.products.ts");
  "routes/api.billing": typeof import("./app/routes/api.billing.ts");
  "routes/api.metrics": typeof import("./app/routes/api.metrics.ts");
  "routes/api.test-db": typeof import("./app/routes/api.test-db.ts");
  "routes/api.health": typeof import("./app/routes/api.health.ts");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.campaign-history": typeof import("./app/routes/app.campaign-history.tsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.tsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.tsx");
  "routes/app.billing": typeof import("./app/routes/app.billing.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.rules": typeof import("./app/routes/app.rules.tsx");
  "routes/app.bulk": typeof import("./app/routes/app.bulk.tsx");
  "routes/app.help": typeof import("./app/routes/app.help.tsx");
};