ALTER TABLE "PriceHistory"
ADD COLUMN IF NOT EXISTS "productId" TEXT;

ALTER TABLE "StagedPrice"
ADD COLUMN IF NOT EXISTS "productId" TEXT;

ALTER TABLE "ScheduledJob"
ADD COLUMN IF NOT EXISTS "title" TEXT NOT NULL DEFAULT 'Scheduled Campaign';

ALTER TABLE "ScheduledJob"
ADD COLUMN IF NOT EXISTS "productCount" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "ScheduledJob"
ADD COLUMN IF NOT EXISTS "products" JSONB;